server:
  port: 8080

springdoc:
  api-docs.path: /api-docs

spring:
  application:
    name: "invoice-webapp"
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:mariadb://localhost/InvoiceDatabase?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver

  jackson:
    mapper:
      accept-case-insensitive-enums: true

  output:
    ansi:
      enabled: ALWAYS

  main:
    banner-mode: off