server:
  port: 8080

springdoc:
  api-docs.path: /api-docs

spring:
  application:
    name: "invoice-webapp"

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: validate
    show-sql: true

  datasource:
    url: jdbc:mariadb://localhost:3306/invoiceapp
    username: invoiceapp_user
    password: invoiceapp_pass
    driver-class-name: org.mariadb.jdbc.Driver

  jackson:
    mapper:
      accept-case-insensitive-enums: true

  output:
    ansi:
      enabled: ALWAYS

  flyway:
    enabled: true
    url: jdbc:mariadb://localhost:3306/invoiceapp
    user: invoiceapp_user
    password: invoiceapp_pass
    locations:
      - classpath:db/migration
      - classpath:db/test-data
    baseline-on-migrate: true
    baseline-version: 0
    validate-on-migrate: true

  cache:
    caffeine:
      spec: initialCapacity=100,maximumSize=300,expireAfterWrite=300s
    cache-names:
        - search-invoices
        - get-persons
        - get-person-statistics
        - get-invoice-statistics
        - get-seller-invoices
        - get-buyer-invoices

logging:
  level:
    org.springframework.cache: trace

management:
  endpoint:
    prometheus:
      access: read-only
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  prometheus:
    metrics:
      export:
        enabled: true

otel:
  resource:
    attributes:
      service.name: ${spring.application.name}
  exporter:
    otlp:
      protocol: grpc
      endpoint: http://localhost:4317
  metrics:
    exporter: none
  logs:
    exporter: none
  traces:
    exporter: otlp

jwt:
  expiration: 86400000
