import person.http

### Create Person
run #Create Person

### Create Invoice
POST {{hostname}}/api/invoice
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "invoiceNumber": {{$random.integer(100000000, 999999999)}},
  "issued": "1999-01-01",
  "dueDate": "2035-10-10",
  "product": "doprava",
  "price": 2500,
  "vat": "21",
  "note": "note",
  "buyerId": 1,
  "sellerId": 2
}

> {%
    client.test("Request was successful", function () {
        client.assert(response.status === 201, "Response status should be 201");
        client.log("id: " + response.body.id);
        client.global.set("invoiceId", response.body.id)
    });
%}

### Get Invoice detail
GET {{hostname}}/api/invoice/{{invoiceId}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}

> {%
    client.test("Request was successful", function () {
        client.assert(response.status === 200, "Response status should be 200");
    });
%}

### Search Invoices
GET {{hostname}}/api/invoices
    ?page=0
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}

> {%
    client.test("Request was successful", function () {
        client.assert(response.status === 200, "Response status should be 200");
    });
%}

### Update Invoice
PUT {{hostname}}/api/invoice/{{invoiceId}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "invoiceNumber": {{$random.integer(100000000, 999999999)}},
  "issued": "1999-01-01",
  "dueDate": "2035-10-10",
  "product": "dopravaaa",
  "price": 650,
  "vat": "16",
  "note": "noteee",
  "buyerId": 1,
  "sellerId": 2
}

> {%
    client.test("Request was successful", function () {
        client.assert(response.status === 200, "Response status should be 200");
    });
%}

### Delete Invoice
DELETE {{hostname}}/api/invoice/{{invoiceId}}
Content-Type: application/json
Authorization: Bearer {{auth_token}}

> {%
    client.test("Request was successful", function () {
        client.assert(response.status === 204, "Response status should be 204");
    });
%}

### Get invoice statistics
GET {{hostname}}/api/invoices/statistics
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}

> {%
    client.test("Request was successful", function () {
        client.assert(response.status === 200, "Response status should be 200");
    });
%}


### Get all invoices of seller by identificationNumber
GET {{hostname}}/api/identification/{{identificationNumber}}/sales
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}

> {%
    client.test("Request was successful", function () {
        client.assert(response.status === 200, "Response status should be 200");
    });
%}

### Get all invoices of buyer by identificationNumber
GET {{hostname}}/api/identification/{{identificationNumber}}/purchases
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}

> {%
    client.test("Request was successful", function () {
        client.assert(response.status === 200, "Response status should be 200");
    });
%}
###