### Create Person
POST {{hostname}}/api/person
Accept: application/json
Content-Type: application/json

{
  "name": "Strejc Pompo",
  "identificationNumber": "{{$random.integer(10000000, 99999999)}}",
  "taxNumber": "CZ123456",
  "accountNumber": "123456789",
  "bankCode": "1234",
  "iban": "CZ123456789",
  "telephone": "+420123456789",
  "mail": "person@test.org",
  "street": "street",
  "zip": "12345",
  "city": "city",
  "country": "CZECHIA"
}

> {%
    client.test("Request was successful", function () {
        client.assert(response.status === 201, "Response status should be 201");
        client.log("id: " + response.body._id);
        client.global.set("personId", response.body._id);
        client.global.set("identificationNumber", response.body.identificationNumber);
    });
%}

### Get Person
GET {{hostname}}/api/person/{{personId}}
Accept: application/json
Content-Type: application/json

> {%
    client.test("Request was successful", function () {
        client.assert(response.status === 200, "Response status should be 200");
    });
%}

### Get total count of Persons
GET {{hostname}}/api/persons/total
Accept: application/json
Content-Type: application/json

> {%
    client.test("Request was successful", function () {
        client.assert(response.status === 200, "Response status should be 200");
    });
%}

### Search Persons
GET {{hostname}}/api/persons
    ?page=0
    &size=2
Accept: application/json
Content-Type: application/json

> {%
    client.test("Request was successful", function () {
        client.assert(response.status === 200, "Response status should be 200");
    });
%}

### Update Person
PUT {{hostname}}/api/person/{{personId}}
Accept: application/json
Content-Type: application/json

{
  "name": "Rumburak",
  "accountNumber": "987654321",
  "bankCode": "4321",
  "iban": "CZ987654321",
  "telephone": "+421987654321",
  "mail": "test@person.com",
  "street": "avenue",
  "zip": "54321",
  "city": "town",
  "country": "SLOVAKIA"
}

### Delete Person
DELETE {{hostname}}/api/person/{{personId}}
Content-Type: application/json

> {%
    client.test("Request was successful", function () {
        client.assert(response.status === 204, "Response status should be 204");
    });
%}

### Get person statistics
GET {{hostname}}/api/persons/statistics
Accept: application/json
Content-Type: application/json

> {%
    client.test("Request was successful", function () {
        client.assert(response.status === 200, "Response status should be 200");
    });
%}
###