name: InvoiceManager CI
on:
  push:
    branches:
      - "*"
      - "*/*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        working-directory: invoice-server-starter
        run: mvn -B compile

      - name: Run tests
        working-directory: invoice-server-starter
        run: mvn -B test --no-transfer-progress